### GET request to example server
GET http://localhost:8080/api/movies

### POST request to add a new movie
POST http://localhost:8080/api/movies
Content-Type: application/json
Accept: application/json

{
  "title": "Inception"
}